#@formatter:off
name: cache_storage_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  envied: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.12
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  get_it: ^8.0.3
  go_router: ^15.1.2

  intl: ^0.19.0
  intl_utils: 2.8.6
  jailbreak_root_detection: ^1.1.6
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.4+1
  logger: ^2.5.0
  onix_flutter_bloc: 0.0.5-beta.1
  onix_flutter_core: 0.0.6-beta.4
  onix_flutter_core_models: 0.0.3-beta.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
  hive_ce: ^2.11.2
  hive_ce_flutter: ^2.3.1
  objectbox: 4.1.0
  objectbox_flutter_libs: 4.1.0
  sembast: ^3.8.3
#  realm_dart: 20.0.1
  realm: 20.0.1
  drift: ^2.23.1
  drift_flutter: ^0.2.3
  floor: ^1.4.1
#  isar: ^3.1.0+1
#  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  import_sorter: ^4.6.0
  test: ^1.25.8
  envied_generator: ^1.1.1
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.14.3
#  isar_generator: ^3.1.0+1
#  hive_generator: ^2.0.1
  hive_ce_generator: ^1.8.1
  objectbox_generator: 4.1.0
  floor_generator: ^1.4.1
  drift_dev: ^2.23.1
#  realm_generator: 20.0.1

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  

    # To add assets to your application, add an assets section, like this:
  assets:
    - assets/launcher_icons/
    #   - images/a_dot_ham.jpeg


    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages

#{flavorizer_injection_config}


flutter_launcher_icons:
  image_path: "assets/launcher_icons/ic_launcher.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_intl:
  enabled: true
  arb_dir: lib/app/localization/l10n
  output_dir: lib/app/localization/generated
  
#generated with mason