// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:cache_storage_demo/data/source/local/hive_cache/hive_cache_record.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCacheRecordAdapter());
  }
}
