// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:cache_storage_demo/data/source/local/hive_adapters/hive_adapters.dart';
import 'package:hive_ce/hive.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(HiveCacheRecordAdapter());
    registerAdapter(HiveMetaRecordAdapter());
    registerAdapter(ProductHOAdapter());
  }
}
